image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  BUILD_CONTAINER_IMAGE: $CI_REGISTRY/kaplan2539/baumeister

before_script:
  - echo "CI_BUILD_ID=$CI_BUILD_ID"
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
  - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
  - echo "CI_BUILD_REF_NAME=$CI_BUILD_REF_NAME"
  - echo "BUILD_CONTAINER_IMAGE=$BUILD_CONTAINER_IMAGE"
  - apk update && apk add wget

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $BUILD_CONTAINER_IMAGE
    - ./build.sh

  artifacts:
    paths:
      - output/
